version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    volumes:
      - './mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=catadoptionAdmin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=catadoption
    container_name: catadoption_mongodb
    image: mongo:latest
  api: 
    depends_on:
      - mongo
    ports: 
      - '3033:${PORT}'
    container_name: catadoption_api
    build: .
    environment:
      - NODE_ENV
      - PORT
      - MONGODB_USER
      - MONGODB_PASSWORD
      - MONGODB_DBNAME
      - MONGODB_HOST=mongo
      - JWT_SECRET
      - ADMIN_USER_EMAIL